Add pdjson2metadata

diff --git a/genericjobs/wfs-generic-job b/genericjobs/wfs-generic-job
--- a/genericjobs/wfs-generic-job
+++ b/genericjobs/wfs-generic-job
@@ -25,7 +25,7 @@ EOF
      --capath $X509_CERTIFICATES \
      --data @wfs-job-aborted.json \
      https://wfs-pro.dune.hep.ac.uk/wfa-cgi/job_aborted_$1
-     
+
   exit 1
 }
 
@@ -90,14 +90,15 @@ export X509_CERTIFICATES=${X509_CERTIFICATES:-/etc/grid-security/certificates/}
 # Check requirements are present
 
 if [ ! -r "$X509_USER_PROXY" ] ; then
+ # Stop if proxy file is missing or deleted
  echo "Cannot read X509_USER_PROXY file = $X509_USER_PROXY"
- exit
+ exit 1
 fi
 
 curl --version
 if [ $? -ne 0 ] ; then
  echo Failed running curl
- exit
+ exit 1
 fi
 
 cat <<EOF >wfs-send-heartbeat.json
@@ -112,7 +113,7 @@ EOF
 
 while :
 do
-  # Stop if proxy file is missing or deleted
+  # Stop if JSON file is missing or deleted
   if [ ! -r wfs-send-heartbeat.json ] ; then
     exit 1
   fi
@@ -172,11 +173,15 @@ if [ "$http_code" != "200" ] ; then
   job_aborted $http_code get_stage
 fi
 
-## Start of temporary Rucio client install. Eventually this
-## section can be removed once we can get Rucio from cvmfs
+## Start of temporary Rucio/MetaCat client install. Eventually this
+## section can be removed once we can get Rucio and MetaCat from cvmfs
 (
+
+#
+# Rucio install
+#
 ## These three lines can be used to use the installed Rucio client
-export RUCIO_HOME=$PWD/rucio-local
+export RUCIO_HOME=$PWD/rucio-home
 export PATH="$RUCIO_HOME/bin:$PATH"
 export PYTHONPATH="$RUCIO_HOME/lib/python3.6/site-packages:/usr/lib64/python3.6/site-packages"
 ##
@@ -202,10 +207,49 @@ rucio --version
 if [ $? != 0 ] ; then
   job_aborted 900 'Rucio install fails'
 fi
-)
-## End of Rucio install section
 
 #
+# MetaCat install
+#
+## These five lines can be used to use the installed MetaCat client
+export METACAT_HOME=$PWD/metacat-home
+export PATH="$METACAT_HOME/bin:$PATH"
+export PYTHONPATH="$METACAT_HOME/lib/python3.6/site-packages:$PYTHONPATH"
+export METACAT_AUTH_SERVER_URL=https://metacat.fnal.gov:8143/auth/dune
+export METACAT_SERVER_URL=https://metacat.fnal.gov:9443/dune_meta_demo/app
+##
+
+mkdir -p $METACAT_HOME
+#git clone https://github.com/ivmfnal/metacat.git
+mkdir -p metacat-github
+( 
+  cd metacat-github 
+  curl --location https://github.com/ivmfnal/metacat/tarball/main \
+    | tar -xz --strip-components 1 
+  python3 setup.py install --prefix=$METACAT_HOME 
+)
+metacat version
+if [ $? != 0 ] ; then
+  job_aborted 900 'MetaCat install fails'
+fi
+
+# This requires $X509_USER_PROXY is set already
+echo "X509_USER_PROXY=$X509_USER_PROXY"
+ls -lt $X509_USER_PROXY
+# Login puts a token in $HOME/.token_library (what if shared between jobs???)
+metacat auth login -m x509 amcnab
+metacat auth whoami
+if [ $? != 0 ] ; then
+  job_aborted 900 'MetaCat whoami fails'
+fi
+
+)
+if [ $? != 0 ] ; then
+  # Exit/aborts inside subshell just exit the subshell with a non-zero code
+  # So we exit the generic job script properly here
+  exit 1
+fi
+## End of Rucio / MetaCat install section
 
 tar xvf wfs-files.tar
 
@@ -349,26 +393,77 @@ echo "Using $output_rse for output, out of $WFS_OUTPUT_RSE_LIST"
 cat $WFS_PATH/wfs-outputs.txt | (
 
 # Because in a subshell, we can change paths to use temporary Rucio install
-export RUCIO_HOME=$PWD/rucio-local
+export RUCIO_HOME=$PWD/rucio-home
 export PATH="$RUCIO_HOME/bin:$PATH"
 export PYTHONPATH="$RUCIO_HOME/lib/python3.6/site-packages:/usr/lib64/python3.6/site-packages"
+# and add MetaCat
+export METACAT_HOME=$PWD/metacat-home
+export PATH="$METACAT_HOME/bin:$PATH"
+export PYTHONPATH="$METACAT_HOME/lib/python3.6/site-packages:$PYTHONPATH"
+export METACAT_AUTH_SERVER_URL=https://metacat.fnal.gov:8143/auth/dune
+export METACAT_SERVER_URL=https://metacat.fnal.gov:9443/dune_meta_demo/app
 
 while read dataset scope fn
 do
-  echo "Metadata first? Would be $fn.json"
-  echo
+  file_size=`wc --bytes "workspace/$fn" | cut -f1 -d' '`
 
-  echo "Upload $scope:$fn"
-  rucio --verbose -a test upload --rse "$output_rse" \
-        --lifetime 86400 --scope "$scope" --name "$fn" "workspace/$fn" 
-  echo "rucio upload returns $?"
+  # Make the JSON to send, including the file's JSON
+  echo '{ "workflow" : {' > tmp.json
 
-  if [ $? = 0 ] ; then
-    echo "Add $scope:$fn to $dataset"
-    rucio --verbose -a test attach "$dataset" "$scope:$fn"
-    echo "rucio attach returns $?"
+  echo "\"site_name\" : \"$WFS_SITE_NAME\"," >> tmp.json
+  echo "\"request_id\" : $WFS_REQUEST_ID," >> tmp.json
+  echo "\"stage_id\" : $WFS_STAGE_ID," >> tmp.json
+  echo "\"hostname\" : \"$HOSTNAME\" }," >> tmp.json
+
+  echo "\"size\" : $file_size," >> tmp.json
+  echo "\"namespace\" : \"$scope\"," >> tmp.json
+  echo "\"name\" : \"$fn\"" >> tmp.json
+
+# TEMP STUFF WHILE MetaCat REQUIRES DOTS IN metadata KEYS
+  if [ -r "workspace/$fn.json" ] ; then  
+    echo ', "Xmetadata" : ' >> tmp.json  
+    cat "workspace/$fn.json" >> tmp.json
   fi
- 
+  # This optional key is not currently optional ...
+  echo ', "metadata" : { "dum.my" : "placeholder" } ' >> tmp.json
+# END TEMP STUFF
+
+#  if [ -r "workspace/$fn.json" ] ; then  
+#    echo ', "metadata" : ' >> tmp.json  
+#    cat "workspace/$fn.json" >> tmp.json
+#  else
+#    # This optional key is not currently optional ...
+#    echo ', "metadata" : { "dum.my" : "placeholder" } ' >> tmp.json
+#  fi
+
+  echo '}' >> tmp.json
+
+  echo "==== Start MetaCat JSON for $fn ===="
+  cat tmp.json
+  echo "==== End MetaCat JSON for $fn ===="
+
+  echo "Declare file in MetaCat"
+  echo "metacat file declare --json tmp.json $dataset"
+  metacat file declare --json tmp.json "$dataset"
+  if [ $? = 0 ] ; then
+    echo "Upload $scope:$fn"
+    rucio --verbose upload --rse "$output_rse" \
+          --lifetime 86400 --scope "$scope" --name "$fn" "workspace/$fn"
+    if [ $? = 0 ] ; then
+      echo "Add $scope:$fn to $dataset"
+      rucio --verbose attach "$dataset" "$scope:$fn"
+      if [ $? != 0 ] ; then
+        echo "rucio attach fails"
+        job_aborted 900 "rucio attach error"      
+      fi      
+    else
+      echo "rucio upload fails"
+      job_aborted 900 "rucio upload error"      
+    fi
+  else
+    echo "metacat file declare fails"
+    job_aborted 900 "metacat file declare error"
+  fi 
 done
 
 
